### ISSUE TITLE
Update doesn't work ? What is the correct way of updating single notes ?

### ISSUE THREAD

**Issue by MrVhek** [klieret/AnkiPandas#121]
Hi !

I'm not sure why but the code here doesn't work, I have the message: WARNING: Nothing seems to have been changed. Will not do anything!

```
    col = Collection()
    cards = col.cards.merge_notes()
    cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
    how_many_updated: int = 0
    for cnt in range(cards.shape[0]):
        try:
            print(cards.iloc[cnt][19])
            print(cards.iloc[cnt][19][0])
            kdlt_num: float = float(cards.iloc[cnt][19][0])
            if cards.iloc[cnt][19][11] != "":
                base_chap: int = int(cards.iloc[cnt][19][11])
            else:
                base_chap: int = 0
            cards.iloc[cnt][19][11] = str(KDLT_to_num(kdlt_num))
            print(f"{base_chap} updated to {cards.iloc[cnt][19][11]}")
            if str(base_chap) != cards.iloc[cnt][19][11]:
                how_many_updated += 1
            # input()
        except IndexError:
            print(cards.iloc[cnt][19])
    print(f"Finished, updated {how_many_updated} chaps")
    col.cards.update(cards)
    col.write(modify=True)
```

Is this the right way to update a card ? I didn't find an example on this in the documentation...
Thanks for your help !

**Comment by klieret** [comment]
Hmm, could you run the same script with `ankipandas.set_log_level("debug")` on top and send me the output of that?

**Comment by MrVhek** [comment]
Here the debug logs, I updated 187 cards in this example:

```
0 updated to 54
['2222', '<img src="paste-2c5d4f79b9ab4b8da5788c55bab750c8209eff1c.jpg">', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
2222
0 updated to 54
['2223', '<img src="paste-1b9d20864db89a3c4862eea68260eda3bce2ac29.jpg">', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
2223
0 updated to 54
Finished, updated 187 chaps
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
DEBUG: Skipping table notes for writing, because nothing seemed to have changed
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
DEBUG: Skipping table cards for writing, because nothing seemed to have changed
DEBUG: Write: Skipping revs, because it's None.
DEBUG: Now getting & updating info.
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Successfully prepared data for writing.
WARNING: Nothing seems to have been changed. Will not do anything!
```

Here another execution without the logs in the for loop
```
INFO: Searching for database. This might take some time. You can speed this up by specifying a search path or directly entering the path to your database.
WARNING: The search will stop at the first hit, so please verify that the result is correct (for example in case there might be more than one Anki installation)
DEBUG: _find_db: Search path 'C:\\Users\\Arh\\.local\\share\\Anki2' does not exist.
DEBUG: _find_db: Search path 'C:\\Users\\Arh\\Documents\\Anki2' does not exist.
DEBUG: _find_db: Breaking after first hit.
DEBUG: Database found at WindowsPath('C:/Users/Arh/AppData/Roaming/Anki2/Utilisateur 1/collection.anki2').
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x0000025E66657670>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to anki
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x0000025E66657670>
DEBUG: Setting metadata attribute _anki_table to notes
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to anki
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x0000025E66657670>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to ours
Finished, updated 187 chaps
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
DEBUG: Skipping table notes for writing, because nothing seemed to have changed
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
DEBUG: Skipping table cards for writing, because nothing seemed to have changed
DEBUG: Write: Skipping revs, because it's None.
DEBUG: Now getting & updating info.
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Successfully prepared data for writing.
WARNING: Nothing seems to have been changed. Will not do anything!
```

**Comment by klieret** [comment]
Ah, I think I know what is wrong here. 

The property that you are modifying belongs to the `notes` table, not the cards. In fact, you probably only need information from the cards at all because you want to filter by deck.

So what you can do instead, is something along the following lines:

```
cards = col.cards.merge_notes()
cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
# Get the note ids of all cards that you have selected
note_ids = cards.nid  # I think it's called nid (=note id)
# Get all notes that have cards in this deck
selected_notes = col.notes[col.notes.nid.isin(note_ids)]
# Now run the loop from above over the notes (you should be able to run
# exactly the same code - though you can probably do this more elegantly
# with vectorized operations)
...
# now your selected_notes should have been updated
col.notes.update(selected_notes)
col.write(modify=True)
```

**Comment by MrVhek** [comment]
And how do you do the for loop ? I tried: 

 ```
   set_log_level("debug")
    col = Collection()
    cards = col.cards.merge_notes()
    cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
    # Get the note ids of all cards that you have selected
    note_ids = cards.nid  # I think it's called nid (=note id)
    # Get all notes that have cards in this deck
    selected_notes = col.notes[col.notes.nid.isin(note_ids)]
    how_many_updated: int = 0
    for selected_note in range(len(selected_notes)):
        try:
            print(selected_notes.iloc[selected_note][4])
            # print(selected_note[0])
            kdlt_num: float = float(selected_notes.iloc[selected_note][4][0])
            if selected_notes.iloc[selected_note][4][11] != "":
                base_chap: int = int(selected_notes.iloc[selected_note][4][11])
            else:
                base_chap: int = 0
            selected_notes.iloc[selected_note][4][11] = str(KDLT_to_num(kdlt_num))
            # print(f"{base_chap} updated to {selected_notes.iloc[selected_note][4][11]}")
            if str(base_chap) != selected_notes.iloc[selected_note][4][11]:
                how_many_updated += 1
            # input()
        except IndexError:
            print(selected_notes.iloc[selected_note][4])
    print(f"Finished, updated {how_many_updated} chaps")
    col.notes.update(selected_notes)
    col.write(modify=True)
```

But I have the same issue :

```
['2223', '<img src="paste-1b9d20864db89a3c4862eea68260eda3bce2ac29.jpg">', '', '', '', '', '', '', '', '', '', '', '', '', '', '']
Finished, updated 187 chaps
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
DEBUG: Skipping table notes for writing, because nothing seemed to have changed
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
DEBUG: Skipping table cards for writing, because nothing seemed to have changed
DEBUG: Write: Skipping revs, because it's None.
DEBUG: Now getting & updating info.
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Successfully prepared data for writing.
WARNING: Nothing seems to have been changed. Will not do anything!
```

**Comment by klieret** [comment]
The code looks good to me at first glance. 

Ok, let's try the following much simpler snippet (and note that we don't call `write`, but just `summarize_changes` to make sure we don't actually write this out)

```python3
set_log_level("debug")
col = Collection()
cards = col.cards.merge_notes()
cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
note_ids = cards.nid
selected_notes = col.notes[col.notes.nid.isin(note_ids)]
selected_notes[4][11] = "some random string 31415"
col.notes.update(selected_notes)
col.summarize_changes()
# let's also try this (it should be all 'True's)
print(selected_notes.was_modified())
```

Can you show me the output? `summarize_changes` should tell us what `AnkiPandas` *thinks* was modified.

**Comment by MrVhek** [comment]
Very strange: this is giving me errors :

```
    set_log_level("debug")
    col = Collection()
    cards = col.cards.merge_notes()
    cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
    note_ids = cards.nid
    selected_notes = col.notes[col.notes.nid.isin(note_ids)]
    selected_notes.fields_as_columns(inplace=True)
    selected_notes["nfld_Chapitre"] = "some random string 31415"
    col.notes.update(selected_notes)
    col.summarize_changes()
    # let's also try this (it should be all 'True's)
    print(selected_notes.was_modified())
```
```
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:576: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.drop("nflds", axis=1, inplace=True)
C:\Users\Arh\Documents\Travail\Jap\anki.py:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_notes["nfld_Chapitre"] = "some random string 31415"
Traceback (most recent call last):
  File "C:\Users\Arh\Documents\Travail\Jap\anki.py", line 156, in <module>
    main_update_kanji_num_3()
  File "C:\Users\Arh\Documents\Travail\Jap\anki.py", line 100, in main_update_kanji_num_3
    col.notes.update(selected_notes)
  File "C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py", line 147, in update
    raise ValueError(
ValueError: You are trying to update a notes AnkiDataFrame where the fields are in format 'list' with a notes AnkiDataFrame where the fields are in format 'columns'. That doesn't sound like a good idea. However you can still do this using the force=True option. Or you simply ensure that both have the same format using the fields_as_columns() or fields_as_list() method.
```

The first option doesn't work either as it doesn't find the index

```
    set_log_level("debug")
    col = Collection()
    cards = col.cards.merge_notes()
    cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
    note_ids = cards.nid
    selected_notes = col.notes[col.notes.nid.isin(note_ids)]
    print(selected_notes[4])
    selected_notes[4][11] = "some random string 31415"
    col.notes.update(selected_notes)
    col.summarize_changes()
    # let's also try this (it should be all 'True's)
    print(selected_notes.was_modified())
```
```
DEBUG: _find_db: Search path 'C:\\Users\\Arh\\.local\\share\\Anki2' does not exist.
DEBUG: _find_db: Search path 'C:\\Users\\Arh\\Documents\\Anki2' does not exist.
DEBUG: _find_db: Breaking after first hit.
DEBUG: Database found at WindowsPath('C:/Users/Arh/AppData/Roaming/Anki2/Utilisateur 1/collection.anki2').
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x0000018531977670>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to anki
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x0000018531977670>
DEBUG: Setting metadata attribute _anki_table to notes
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to anki
DEBUG: Opening Db from C:\Users\Arh\AppData\Roaming\Anki2\Utilisateur 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x0000018531977670>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to ours
Traceback (most recent call last):
  File "C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\pandas\core\indexes\base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Arh\Documents\Travail\Jap\anki.py", line 156, in <module>
    main_update_kanji_num_2()
  File "C:\Users\Arh\Documents\Travail\Jap\anki.py", line 112, in main_update_kanji_num_2
    print(selected_notes[4])
  File "C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\pandas\core\frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 4
```

In this example I need to update on each note the 11th field on the card based on the 1st field (I have a function that compute the value for the 11th field based on the 1st one). I don't know much about panda so maybe there is a more optimize version.

**Comment by klieret** [comment]
Ah sorry, as the first error message states, you need a 

```python3
selected_notes.fields_as_columns(inplace=True)
```

before  `col.notes.update(selected_notes)`   (to convert it back to having all the field entries as lists in the dataframe). I thought `AnkiPandas` would do that automatically, but apparently it doesn't.

**Comment by klieret** [comment]
Oh and yes, the other strategy probably doesn't work like that, sorry for mistakenly proposing that. Updating columns that contain lists as entries is pretty awkward. 

So how about:

```
set_log_level("debug")
col = Collection()
cards = col.cards.merge_notes()
cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
note_ids = cards.nid
selected_notes = col.notes[col.notes.nid.isin(note_ids)]
selected_notes.fields_as_columns(inplace=True)
selected_notes["nfld_Chapitre"] = "some random string 31415"
# ---- NEW ----
selected_notes.fields_as_columns(inplace=True)
col.notes.update(selected_notes)
col.summarize_changes()
# let's also try this (it should be all 'True's)
print(selected_notes.was_modified())
```

**Comment by MrVhek** [comment]
Ok great this seems to work ! Thanks for your help !

```
    set_log_level("debug")
    col = Collection()
    cards = col.cards.merge_notes()
    cards = cards.query(f"cdeck == 'Les Kanjis dans la tête - Yves Maniettes V1.4'")
    note_ids = cards.nid
    selected_notes = col.notes[col.notes.nid.isin(note_ids)]
    selected_notes.fields_as_columns(inplace=True)
    selected_notes["nfld_Chapitre"] = [
        str(KDLT_to_num(float(kdlt))) for kdlt in selected_notes['nfld_KDLT']
    ]
    # selected_notes["nfld_Chapitre"] = "some random string 31415"
    selected_notes.fields_as_list(inplace=True)
    col.notes.update(selected_notes)
    col.summarize_changes()
    # let's also try this (it should be all 'True's)
    print(selected_notes.was_modified())
```
```
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:620: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.loc[self.mid == mid, "nflds"] = pd.Series(
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:627: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.drop(to_drop, axis=1, inplace=True)
======== notes ========
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
Total rows: 22951
Compared to original version:
Modified rows: 187
Added rows: 0
Deleted rows: 0
======== cards ========
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
Total rows: 40601
Compared to original version:
Modified rows: 0
Added rows: 0
Deleted rows: 0
C:\Users\Arh\.virtualenvs\Jap-fByl1IQl\lib\site-packages\ankipandas\ankidf.py:839: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead.
  inters = set(self_sf.index & other_nids)
nid
1440500504099    False
1440500504100    False
1440500504101    False
1440500504102    False
1440500504103    False
                 ...
1670876364386     True
1670876525199     True
1670876535012     True
1670876547331     True
1670876557678     True
Length: 2389, dtype: bool
```

**Comment by klieret** [comment]
Ah great! I suspect that then maybe there was a bug in your previous implementation with the loop (perhaps the fields didn't get updated properly?)
